/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NurseRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.Utils.AgeCalculator;
import static Business.Utils.Validations.bpstatus;
import static Business.Utils.Validations.hrstatus;
import static Business.Utils.Validations.rrstatus;
import static Business.Utils.Validations.wstatus;
import Business.VitalSigns.VitalSignHistoryOfPatient;
import Business.VitalSigns.VitalSignOfPatient;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JViewport;

/**
 *
 * @author Saurabh
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    private JPanel userProcessContainer;
    private LabTestWorkRequest request;
    private Enterprise enterprise;
    public ProcessWorkRequestJPanel(JPanel userProcessContainer,LabTestWorkRequest requst,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.request=requst;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        wJText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rrJText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hrJText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sbpJText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/submit.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/arrow-back-icon.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Weight(lbs)");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Record Vital Signs");

        jLabel7.setText("Respiratory Rate");

        jLabel8.setText("Heart Rate");

        jLabel9.setText("Systolic Blood Pressure");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jButton2))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(rrJText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hrJText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sbpJText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wJText, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(445, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rrJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(hrJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sbpJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(hrJText.getText().trim().length() == 0 || wJText.getText().trim().length() == 0 || sbpJText.getText().trim().length() == 0 || rrJText.getText().trim().length() == 0){
            JOptionPane.showMessageDialog(null, "All fields madatory.");
            return;
        }else{
            
            try{
                Float.parseFloat(rrJText.getText());
                Float.parseFloat(hrJText.getText());
                Float.parseFloat(sbpJText.getText());
                Float.parseFloat(wJText.getText());
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Enter Valid data.");
                return;
            }
        }
        
        float rr=Float.parseFloat(rrJText.getText());
        float hr=Float.parseFloat(hrJText.getText());
        float bp=Float.parseFloat(sbpJText.getText());
        float w=Float.parseFloat(wJText.getText());

        VitalSignHistoryOfPatient vsh;
        UserAccount patientAccount=request.getAssociatedToAppointmentRequest().getPatient();
        PatientOrganization patOrg=null;
        Patient p=null;
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof PatientOrganization){
                patOrg=(PatientOrganization)org;
                break;
            }
        }
        for(Patient patient:patOrg.getPatientDirectory().getPatientList()){
            if(patient.toString().equals(patientAccount.getEmployee().toString())){
                p=patient;
                break;
            }
        }
        vsh=p.getVsh();        
        VitalSignOfPatient vs=p.getVsh().addVitalSign();
        vs.setPatientHR(hr);
        vs.setPatientRR(rr);
        vs.setPatientSBP(bp);
        vs.setPatientW(w);
        
        request.setStatus("Processed");
        request.setResolveDate(new Date());
        float years=AgeCalculator.calculategetage(new Date(), p.getDateOfBirth());
        int age=(int) (years/1);
            boolean rrstatusflag;
            boolean hrstatusflag;
            boolean wstatusflag;
            boolean bpstatusflag;
            bpstatusflag = bpstatus(bp,age);
            rrstatusflag = rrstatus(rr,age);
            hrstatusflag = hrstatus(hr,age);
            wstatusflag = wstatus(w,age);
            if((bpstatusflag && rrstatusflag && hrstatusflag && wstatusflag)== true){
                request.setTestResult("Normal Vitals"); 
            }
            else{
                request.setTestResult("Abnormal Vitals"); 
            } 
        JOptionPane.showMessageDialog(null, "Request Processed.", "Info", JOptionPane.INFORMATION_MESSAGE);
        backbutton();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        backbutton();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    public void backbutton(){
        
        userProcessContainer.remove(this.getParent().getParent());
        userProcessContainer.remove(this.getParent());
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        JScrollPane jsp=(JScrollPane)component;
        JViewport jv=(JViewport)jsp.getComponent(0);
        NurseWorkAreaJPanel nwjp = (NurseWorkAreaJPanel) jv.getComponent(0);
        nwjp.populateNurseWorkQueueJTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        userProcessContainer.remove(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hrJText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField rrJText;
    private javax.swing.JTextField sbpJText;
    private javax.swing.JTextField wJText;
    // End of variables declaration//GEN-END:variables
}
