/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JScrollPane;

/**
 *
 * @author Saurabh
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private PatientOrganization patientOrganization;
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization doctorOrganization,Enterprise enterprise,EcoSystem business) {
        initComponents();
        jLabel2.setText(enterprise.getName());
        this.userProcessContainer=userProcessContainer;
        currentDateAndTime();
        this.enterprise=enterprise;
        this.userAccount=account;
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof PatientOrganization){
                patientOrganization=(PatientOrganization) org;
                break;
            }
        }
        createTabsForJTAB(patientOrganization);
    }
    public void createTabsForJTAB(PatientOrganization patientOrganization){
        CheckAppointmentsJPanel cajp=new CheckAppointmentsJPanel(patientOrganization,doctorOrganization,userAccount,enterprise);
        doctorWorkAreajTabbedPane.add("Appointments",cajp);
//        ProcessVisit pv=new ProcessVisit();
//        doctorWorkAreajTabbedPane.add("Visits",pv);
    }
    
    public void currentDateAndTime(){
        
        Thread clock=new Thread(){
            public void run(){
                for(;;){
                    Calendar calender=new GregorianCalendar();
        int month=calender.get(Calendar.MONTH);
        int year=calender.get(Calendar.YEAR);
        int day=calender.get(Calendar.DAY_OF_MONTH);
        String dateText=(month+1)+"/"+day+"/"+year;
        
        int second=calender.get(Calendar.SECOND);
        int minute=calender.get(Calendar.MINUTE);
        int hour=calender.get(Calendar.HOUR);
        int timePeriod=calender.get(Calendar.AM_PM);
        String clockformat;
        if(timePeriod==0){
            clockformat="AM";
        }else{
            clockformat="PM";
        }
        String timeText=hour+":"+minute+":"+(second+1)+" "+clockformat;
        
        
        String dateAndTime=dateText+"  "+timeText;
        dateAndTimeJLabel.setText(dateAndTime);
                    try{
                        sleep(1000);
                    }catch(InterruptedException e){
                        
                    }
                }
            }
        };
        clock.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        doctorWorkAreajTabbedPane = new javax.swing.JTabbedPane();
        dateAndTimeJLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Work Area", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enterprise");

        jLabel2.setText("value");

        doctorWorkAreajTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        doctorWorkAreajTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        dateAndTimeJLabel.setText("date and time");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/create-account-Apps-Live-Messenger-Metro-icon.png"))); // NOI18N
        jButton1.setText("View Your Patients");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorWorkAreajTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateAndTimeJLabel)
                        .addGap(0, 715, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateAndTimeJLabel)
                .addGap(18, 18, 18)
                .addComponent(doctorWorkAreajTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ViewPatientProfileJPanel viewPatientProfileJPanel=new ViewPatientProfileJPanel(userProcessContainer,userAccount,enterprise);
        userProcessContainer.add("viewPatientProfileJPanel",new  JScrollPane(viewPatientProfileJPanel));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateAndTimeJLabel;
    private javax.swing.JTabbedPane doctorWorkAreajTabbedPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    // End of variables declaration//GEN-END:variables
}
