/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AnalyticsAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AccessRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh
 */
public class ManageRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRequestsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem business;
    private Network network;
    private EnterpriseDirectory enterpriseDirectory;
    private PatientOrganization patientOrganization;
    private UserAccount userAccount;
    public ManageRequestsJPanel(JPanel userProcessContainer, UserAccount userAccount,Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business=business;
        this.enterprise = enterprise;
        this.userAccount=userAccount;
        //createAndAddTabinJTAB();
        
        
        createAndAddTabinJTAB();
        populateOrgtable();
        populateAvailabletoRequest();
        
        
    }
    public void createAndAddTabinJTAB(){
        InitialRequests ir=new InitialRequests(userAccount,enterprise);
        jTabbedPane1.add("Requested Access",ir);
        
        RevokedDeclinedAccesss rda=new RevokedDeclinedAccesss(userAccount,enterprise);
        jTabbedPane1.add("Revoked/Declined Access",rda);
        
        GrantedAccess ga=new GrantedAccess(userAccount,enterprise);
        jTabbedPane1.add("Granted Access",ga);
        
        
        
        
    }
    public void populateAvailabletoRequest(){
        DefaultTableModel model = (DefaultTableModel) availableToRequest.getModel();
       // organizationJTable.setRowSorter(new TableRowSorter(model));
        model.setRowCount(0);
        
        for (Network n:business.getNetworkList()){
            enterpriseDirectory=n.getEnterpriseDirectory();
            for(Enterprise e:enterpriseDirectory.getEnterpriseList()){
                for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                    if(o instanceof PatientOrganization){
                        if(!enterprise.getOrganizationDirectory().getOrganizationList().contains(o)){
                            Object[] row = new Object[3];
                            row[0] = n;
                            row[1] = e;
                            row[2] = o;
                            model.addRow(row);
                        }
                         
                    }
                }
            }
           
        }
    }
   
    
    
    
   
    
    public void populateOrgtable(){
        DefaultTableModel model = (DefaultTableModel) orgtable.getModel();
       // organizationJTable.setRowSorter(new TableRowSorter(model));
        model.setRowCount(0);
        for(Organization org:enterprise.getOrganizationDirectory().getOrganizationList()){
            
            Object[] row = new Object[1];
                            row[0] = org;
                           
                            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        availableToRequest = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        requestAccessJButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        orgtable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(255, 255, 255));

        availableToRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Network", "Enterprise", "Patient Org"
            }
        ));
        jScrollPane1.setViewportView(availableToRequest);

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/arrow-back-icon.png"))); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Organization Available to Request Data:");

        requestAccessJButton1.setBackground(new java.awt.Color(0, 0, 0));
        requestAccessJButton1.setForeground(new java.awt.Color(255, 255, 255));
        requestAccessJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Button-Submit-icon.png"))); // NOI18N
        requestAccessJButton1.setText("Make Request");
        requestAccessJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestAccessJButton1ActionPerformed(evt);
            }
        });

        orgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Accessible Organizations"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(orgtable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requestAccessJButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(389, 389, 389)
                                    .addComponent(backJButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(requestAccessJButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this.getParent().getParent());
        userProcessContainer.remove(this.getParent());
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void requestAccessJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestAccessJButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow=availableToRequest.getSelectedRow();
         if (selectedRow < 0){
             JOptionPane.showMessageDialog(null, "Please select  Enteprise for requesting Access.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }else{
             AccessRequest accesRequest=new AccessRequest();
             Network n=(Network)availableToRequest.getValueAt(selectedRow, 0);
             Enterprise ent=(Enterprise)availableToRequest.getValueAt(selectedRow, 1);
             PatientOrganization p=(PatientOrganization)availableToRequest.getValueAt(selectedRow, 2);
             ent.getWorkQueue().getWorkRequestList().add(accesRequest);
             userAccount.getWorkQueue().getWorkRequestList().add(accesRequest);
             accesRequest.setPatientOrganization(p);
             accesRequest.setAccessStatus("Requested");
             accesRequest.setMessage("Access requested for patient data of Enterprise-"+ent+" of Network-"+n);
             accesRequest.setReceiver(null);
             accesRequest.setSender(userAccount);
             accesRequest.setRequestDate(new Date());
             accesRequest.setStatus("Initial");
             JOptionPane.showMessageDialog(null, "Access request sent.");
             
             InitialRequests ir=(InitialRequests)jTabbedPane1.getComponent(0);
             ir.populateInitialRequestTable();
         
         
        }
         
    }//GEN-LAST:event_requestAccessJButton1ActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable availableToRequest;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable orgtable;
    private javax.swing.JButton requestAccessJButton1;
    // End of variables declaration//GEN-END:variables
}
