/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CVSAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import userinterface.CVSAdminRole.ManagePharmacyEmployeeJPanel;
import userinterface.CVSAdminRole.ManagePharmacyUserAccountsJPanel;


/**
 *
 * @author Saurabh
 */

public class CvsAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
//    private PharmacyDirectory pharmacyDirectory;
//    private Business business;
    private Enterprise enterprise;
    private EcoSystem business;
    public CvsAdminWorkAreaJPanel(JPanel upc,Enterprise enterprise,EcoSystem business){//Business b, {
        initComponents();
        this.userProcessContainer=upc;
        this.business=business;
       // this.business=b;
        this.enterprise=enterprise;
       // pharmacyDirectory=b.getPharmacyDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createStoreJButton = new javax.swing.JButton();
        managePharmacyStoreJButton = new javax.swing.JButton();
        managePharmacyEmployeeJButton = new javax.swing.JButton();
        manageUserJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CVS Admin Work Area");

        createStoreJButton.setBackground(new java.awt.Color(0, 0, 0));
        createStoreJButton.setForeground(new java.awt.Color(255, 255, 255));
        createStoreJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/pharmacy-store.png"))); // NOI18N
        createStoreJButton.setText("Create Pharmacy Org");
        createStoreJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStoreJButtonActionPerformed(evt);
            }
        });

        managePharmacyStoreJButton.setBackground(new java.awt.Color(0, 0, 0));
        managePharmacyStoreJButton.setForeground(new java.awt.Color(255, 255, 255));
        managePharmacyStoreJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/manage-store.png"))); // NOI18N
        managePharmacyStoreJButton.setText("Manage Pharmacy Store");
        managePharmacyStoreJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePharmacyStoreJButtonActionPerformed(evt);
            }
        });

        managePharmacyEmployeeJButton.setBackground(new java.awt.Color(0, 0, 0));
        managePharmacyEmployeeJButton.setForeground(new java.awt.Color(255, 255, 255));
        managePharmacyEmployeeJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/user-couple-icon.png"))); // NOI18N
        managePharmacyEmployeeJButton.setText("Manage Employee");
        managePharmacyEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePharmacyEmployeeJButtonActionPerformed(evt);
            }
        });

        manageUserJButton.setBackground(new java.awt.Color(0, 0, 0));
        manageUserJButton.setForeground(new java.awt.Color(255, 255, 255));
        manageUserJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/Male-user-add-icon.png"))); // NOI18N
        manageUserJButton.setText("Manage User");
        manageUserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(createStoreJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePharmacyStoreJButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(managePharmacyEmployeeJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageUserJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(managePharmacyEmployeeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(createStoreJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managePharmacyStoreJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageUserJButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createStoreJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStoreJButtonActionPerformed
        // TODO add your handling code here:
        CreatePharmacyStoreJPanel cpsj=new CreatePharmacyStoreJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("CreatePharmacyStoreJPanel",new JScrollPane(cpsj));
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createStoreJButtonActionPerformed

    private void managePharmacyStoreJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePharmacyStoreJButtonActionPerformed
        // TODO add your handling code here:
        ManagePharmacyJPanel mpjp=new ManagePharmacyJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("ManagePharmacyJPanel",new JScrollPane(mpjp));
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePharmacyStoreJButtonActionPerformed

    private void managePharmacyEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePharmacyEmployeeJButtonActionPerformed
        
        ManagePharmacyEmployeeJPanel  manageEmployee=new ManagePharmacyEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployee", new JScrollPane(manageEmployee));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePharmacyEmployeeJButtonActionPerformed

    private void manageUserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserJButtonActionPerformed
        // TODO add your handling code here:
        ManagePharmacyUserAccountsJPanel manageAccount=new ManagePharmacyUserAccountsJPanel(userProcessContainer, enterprise,business);
        userProcessContainer.add("manageAccount", new JScrollPane(manageAccount));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createStoreJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton managePharmacyEmployeeJButton;
    private javax.swing.JButton managePharmacyStoreJButton;
    private javax.swing.JButton manageUserJButton;
    // End of variables declaration//GEN-END:variables
}
