/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AnalystRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AnalystStaff;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Saurabh
 */
public class AnalystWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalystWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private AnalystStaff analystStaff;
    private Enterprise enterprise;
    public AnalystWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, AnalystStaff organization,Enterprise enterprise ,EcoSystem business) {
        initComponents();
        
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.analystStaff=organization;
        this.enterprise=enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        graphicalReportingJButton = new javax.swing.JButton();
        textualReportingJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Analyst Work Area");

        graphicalReportingJButton.setBackground(new java.awt.Color(0, 0, 0));
        graphicalReportingJButton.setForeground(new java.awt.Color(255, 255, 255));
        graphicalReportingJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/graphical-reporting.png"))); // NOI18N
        graphicalReportingJButton.setText("Graphical Reporting");
        graphicalReportingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphicalReportingJButtonActionPerformed(evt);
            }
        });

        textualReportingJButton.setBackground(new java.awt.Color(0, 0, 0));
        textualReportingJButton.setForeground(new java.awt.Color(255, 255, 255));
        textualReportingJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/textual.png"))); // NOI18N
        textualReportingJButton.setText("Textual Reporting");
        textualReportingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textualReportingJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graphicalReportingJButton)
                        .addGap(61, 61, 61)
                        .addComponent(textualReportingJButton)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(graphicalReportingJButton)
                    .addComponent(textualReportingJButton))
                .addContainerGap(239, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void graphicalReportingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphicalReportingJButtonActionPerformed
        // TODO add your handling code here:
        GraphicalReportingJPanel graphicalReportingJPanel = new GraphicalReportingJPanel(userProcessContainer,userAccount ,enterprise);
        userProcessContainer.add("graphicalReportingJPanel", new JScrollPane(graphicalReportingJPanel));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_graphicalReportingJButtonActionPerformed

    private void textualReportingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textualReportingJButtonActionPerformed
        // TODO add your handling code here:
         TextualReportingJPanel textualReportinhJPanel = new TextualReportingJPanel(userProcessContainer,userAccount ,enterprise);
        userProcessContainer.add("textualReportinhJPanel", new JScrollPane(textualReportinhJPanel));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_textualReportingJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton graphicalReportingJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton textualReportingJButton;
    // End of variables declaration//GEN-END:variables
}
