/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Community.Community;
import Business.Community.CommunityProfile;
import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Saurabh
 */
public class CommunityJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;
    private UserAccount userAccount;
    private Community community;
    public CommunityJPanel(JPanel userProcessContainer,Patient p,UserAccount userAccount,Community community) {
        initComponents();
        this.community=community;
        this.patient=patient;
        this.userAccount=userAccount;
        this.userProcessContainer=userProcessContainer;
       
        for(CommunityProfile cp:community.getListOfCommunityMembers()){
            if(cp.getUserAccount().equals(userAccount)){
                joinJButton.setEnabled(false);
                leaveJButton.setEnabled(true);
            }else{
                joinJButton.setEnabled(true);
                leaveJButton.setEnabled(false);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        joinJButton = new javax.swing.JButton();
        leaveJButton = new javax.swing.JButton();
        setProfilePicjButton = new javax.swing.JButton();
        profilePicJLable = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        joinJButton.setBackground(new java.awt.Color(0, 0, 0));
        joinJButton.setForeground(new java.awt.Color(255, 255, 255));
        joinJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/join.png"))); // NOI18N
        joinJButton.setText("Join");
        joinJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinJButtonActionPerformed(evt);
            }
        });

        leaveJButton.setBackground(new java.awt.Color(0, 0, 0));
        leaveJButton.setForeground(new java.awt.Color(255, 255, 255));
        leaveJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/leave.png"))); // NOI18N
        leaveJButton.setText("Leave");
        leaveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveJButtonActionPerformed(evt);
            }
        });

        setProfilePicjButton.setBackground(new java.awt.Color(0, 0, 0));
        setProfilePicjButton.setForeground(new java.awt.Color(255, 255, 255));
        setProfilePicjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/set-profile-pic.png"))); // NOI18N
        setProfilePicjButton.setText("Set Profile Pic");
        setProfilePicjButton.setToolTipText("Size should be 310 X 310");
        setProfilePicjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setProfilePicjButtonActionPerformed(evt);
            }
        });

        profilePicJLable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        profilePicJLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        profilePicJLable.setPreferredSize(new java.awt.Dimension(34, 34));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/members.png"))); // NOI18N
        jButton1.setText("View Community Members and Stories");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/view-profile-pic.png"))); // NOI18N
        jButton2.setText("View Profile Pic");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Community");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/arrow-back-icon big.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/online-community-banner.jpg"))); // NOI18N

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Icons/remove-profile-pic.png"))); // NOI18N
        jButton4.setText("Remove Profile Pic");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leaveJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(joinJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(setProfilePicjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(profilePicJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(joinJButton)
                            .addComponent(setProfilePicjButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leaveJButton)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(profilePicJLable, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void joinJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinJButtonActionPerformed
        // TODO add your handling code here:
        boolean isAlreadyJoined=false;
        
        if(!community.getListOfCommunityMembers().isEmpty()){
            for(CommunityProfile cp:community.getListOfCommunityMembers()){
            if(cp.getUserAccount().equals(userAccount)){
                isAlreadyJoined=true;
                 break;
            }
               
            }
            
        }
        if(isAlreadyJoined){
            JOptionPane.showMessageDialog(null,"You are already connected to the community");
                return;
        }
            if(!isAlreadyJoined){
                JoinCommunityJPanel joinCommunity=new JoinCommunityJPanel(userProcessContainer,userAccount,community);
        userProcessContainer.add("joinCommunity",new  JScrollPane(joinCommunity));
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
         
            }
    }//GEN-LAST:event_joinJButtonActionPerformed

    private void setProfilePicjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setProfilePicjButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser jf=new JFileChooser();
        FileNameExtensionFilter newFil=new FileNameExtensionFilter("Image file", "png","jpg","gif");
        jf.setFileFilter(newFil);
        jf.showOpenDialog(null);
        File f=jf.getSelectedFile();
        if(f!=null){
         //   String fileName=f.getAbsolutePath();
            
//            ImageIcon ico = new ImageIcon(fileName);
//            profilePicJLable.setIcon(ico);
            for(CommunityProfile cp:community.getListOfCommunityMembers()){
            if(cp.getUserAccount().equals(userAccount)){
           //     cp.setProfilePicture(fileName);
                cp.setProfilePictureFile(f);
                    break;
            }
            }
        }
        
        
        
        
    }//GEN-LAST:event_setProfilePicjButtonActionPerformed

    private void leaveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveJButtonActionPerformed
        // TODO add your handling code here:
        CommunityProfile c=null;
        for(CommunityProfile cp:community.getListOfCommunityMembers()){
            if(cp.getUserAccount().getEmployee().toString().equals(userAccount.getEmployee().toString())){
                c=cp;
                break;
            }
        }
        int answer=JOptionPane.showConfirmDialog(null,"Are you sure you want to Leave?");
        if(answer==JOptionPane.YES_OPTION){
            community.leaveCommunity(c);
        joinJButton.setEnabled(true);
        }
        else{
            return;
        }
        
    }//GEN-LAST:event_leaveJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:if(!community.getListOfCommunityMembers().isEmpty()){
            boolean notPresent=false;
            boolean present=false;
        if(community.getListOfCommunityMembers().isEmpty()){
            JOptionPane.showMessageDialog(null,"No members to view");
            return;
        }else{
            for(CommunityProfile cp:community.getListOfCommunityMembers()){
            if(cp.getUserAccount().equals(userAccount)){
                present=true;
                break;
                
            }
            
        } 
            if(!present){
                JOptionPane.showMessageDialog(null,"You cannot access community without being a member.Join Community first to enter");
                    return;
            }
            if(present){
                    ViewCommunityMembersJPanel vcmjp=new ViewCommunityMembersJPanel(userProcessContainer,userAccount,community);
                userProcessContainer.add("vcmjp",new  JScrollPane(vcmjp));
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                    
            }
        }
        
                
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for(CommunityProfile cp:community.getListOfCommunityMembers()){
            if(cp.getUserAccount().equals(userAccount)){
                if(cp.getProfilePictureFile()!=null){
//                String fileName=cp.getProfilePicture();
//             ImageIcon ico = new ImageIcon(fileName);
//             profilePicJLable.setIcon(ico);
                    ImageIcon ico = new ImageIcon(cp.getProfilePictureFile().toString());
                    profilePicJLable.setIcon(ico);
             
                break;
                }
            
                
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        for(CommunityProfile cp:community.getListOfCommunityMembers()){
            if(cp.getUserAccount().equals(userAccount)){
                cp.setProfilePicture("");
                String fileName=cp.getProfilePicture();
                ImageIcon ico = new ImageIcon(fileName);
                profilePicJLable.setIcon(ico);
                break;
            }
        }
            
                
            
    }//GEN-LAST:event_jButton4ActionPerformed
public void backAction(){
        
        userProcessContainer.remove(this.getParent().getParent());
        userProcessContainer.remove(this.getParent());
        userProcessContainer.remove(this);
        
        

        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton joinJButton;
    private javax.swing.JButton leaveJButton;
    private javax.swing.JLabel profilePicJLable;
    private javax.swing.JButton setProfilePicjButton;
    // End of variables declaration//GEN-END:variables
}
