/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientRole;

import Business.Patient.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh
 */
public class MyLabTestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyLabTestsJPanel
     */
    private Patient patient;
    private UserAccount userAccount;
    public MyLabTestsJPanel(Patient patient,UserAccount userAccount) {
        initComponents();
        this.patient=patient;
        this.userAccount=userAccount;
        populatelabTestsJTable();
    }

    public void populatelabTestsJTable(){
        DefaultTableModel model = (DefaultTableModel) labTestsJTable.getModel();
        LabTestWorkRequest labTestWorkRequest=null;
        model.setRowCount(0);
       
        for (WorkRequest request :userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof LabTestWorkRequest){
                if(request.getStatus().equals("Processed")){
                        labTestWorkRequest=(LabTestWorkRequest) request;
                        Object[] row = new Object[9];
                        row[0] = labTestWorkRequest.getAssociatedToAppointmentRequest();
                        row[1] = labTestWorkRequest.getRequestDate();
                        row[2] = labTestWorkRequest.getSender();
                        row[3] = labTestWorkRequest.getReceiver();
                        row[4] = labTestWorkRequest.getComment();
                        row[5] = labTestWorkRequest.getMessage();
                        row[6] = labTestWorkRequest.getStatus();
                        row[7] = labTestWorkRequest.getTestResult();
                        row[8] = labTestWorkRequest.getResolveDate();
                        model.addRow(row);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        labTestsJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        labTestsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "For Appointment", "Request Date", "Sender", "Processed By", "Type", "Message", "Status", "Result", "Resolved Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        labTestsJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(labTestsJTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable labTestsJTable;
    // End of variables declaration//GEN-END:variables
}
